### ISSUE TITLE
Consume Eliot logs from Tahoe-LAFS

### ISSUE THREAD

**Issue by exarkun** [gridsync/gridsync#173]
Tahoe-LAFS recently gained some amount of structured logging using the Eliot logging library.  Such logs are not written anywhere by default but can be written to a file with a command line argument.  Development is currently in progress to expose these logs via a WebSocket-based interface served the the Tahoe-LAFS node, allowing the logs to be consumed without ever committing them to disk.

GridSync could consume this WebSocket API to receive these Eliot log events from the Tahoe-LAFS node.  This would be useful if information is being collected to diagnose a Tahoe-LAFS misbehavior (either by the user or to create a report to send upstream).

**Comment by exarkun** [comment]
Considerations for this:
* Does the Tahoe-LAFS installation in use actually have this endpoint?
* What quantity of these logs should be kept around in memory?  They can be quite voluminous.

I want to specifically leave out of scope:
* Any GUI for showing these to the user
* Any report generation to bundle these up for transmission elsewhere
* Any tricks to reduce in-memory size of the Eliot logs in the GridSync process

but that all seems like good stuff to build on this.

**Comment by exarkun** [comment]
Initial implementation thoughts:
* gridsync.tahoe.Tahoe gains a new attribute that refers to something like an `WebSocketEliotLogReader`.
* `WebSocketEliotLogReader` is responsible for managing a WebSocket client connection to the Tahoe-LAFS process.
* `WebSocketEliotLogReader` passes received Eliot log messages onwards, perhaps using `pyqtSignal`, similar to the way `gridsync.monitor.Monitor` exposes events it is aware of.
* Some other part of GridSync that is concerned with buffering debug logs registers its interest in the relevant signals, receives the Eliot messages, and buffers.  This suggests the buffer limiting logic is actually also out of scope for this work.

**Comment by crwood** [comment]
Thanks for opening this. :)

> - gridsync.tahoe.Tahoe gains a new attribute that refers to something like an `WebSocketEliotLogReader`.
> - `WebSocketEliotLogReader` is responsible for managing a WebSocket client connection to the Tahoe-LAFS process.
> - `WebSocketEliotLogReader` passes received Eliot log messages onwards, perhaps using `pyqtSignal`, similar to the way `gridsync.monitor.Monitor` exposes events it is aware of.
> - Some other part of GridSync that is concerned with buffering debug logs registers its interest in the relevant signals, receives the Eliot messages, and buffers. This suggests the buffer limiting logic is actually also out of scope for this work.

Yes, this is more-or-less what I was thinking -- but sans the `pyqtSignal`s usage. Reason being, I recall us deciding that the logs would _not_ be used to feed UI updates directly (which is what `pyqtSignal` is typically used for) and that we'd provide a separate (but probably similar) "streaming magic-folder status" websocket endpoint for this later on. In other words, the goal, for now, is simply to allow Gridsync to collect (and, depending on where/when we do it) apply any remaining/needed privacy filters to the raw eliot logs before the user exports them elsewhere via the UI. To that end, I was originally imagining just adding a `collections.deque(maxlen=10000)` (or whatever limit we choose) _somewhere_ in Gridsync that `WebSocketEliotLogReader` could `append()` lines/messages to (and from which the log exporter UI would read later if/when the user needs to export).

>What quantity of these logs should be kept around in memory? They can be quite voluminous.

I'm not quite sure what this value should be (yet) but I agree they can get quite voluminous... On that note, is there any way that those "`magic-folder:iteration`-every-second" messages could be suppressed without adversely affecting the causation-chain that eliot attempts to track and later visualize? In my prior testing, those messages occupied the overwhelming majority of the log's contents (and, if we could do away with them, the signal-to-noise ratio would probably be a lot higher -- and our message-limit could probably afford to be a lot lower).

**Comment by exarkun** [comment]
> On that note, is there any way that those "magic-folder:iteration-every-second" messages could be suppressed without adversely affecting the causation-chain that eliot attempts to track and later visualize?

We could probably throw out whole trees rooted at that action if the tree ends up not containing any meaningful activity (nothing found in any of the various queues to work on).

On the other hand, I've been thinking that it's pretty silly that magic-folder wakes itself up every second when it _knows_ there is no work to do.  If we were a small increment smarter about scheduling "iteration" then all those log messages would just go away, along with the associated process wakeup and CPU time.

**Comment by exarkun** [comment]
> Yes, this is more-or-less what I was thinking -- but sans the pyqtSignals usage. Reason being, I recall us deciding that the logs would not be used to feed UI updates directly (which is what pyqtSignal is typically used for) and that we'd provide a separate (but probably similar) "streaming magic-folder status" websocket endpoint for this later on. In other words, the goal, for now, is simply to allow Gridsync to collect (and, depending on where/when we do it) apply any remaining/needed privacy filters to the raw eliot logs before the user exports them elsewhere via the UI. 

That works for me.  I was imagining that there _would_ be a UI dedicated to just *showing* the log at some point and it might want signals to drive updates.  It probably makes sense to add those signals when that functionality is added, though.  Actually, I think a general shortcoming of this ticket is that it doesn't exactly define any new user-facing functionality.  I want to do something in Gridsync but I don't feel up to actually adding any user-facing UI in my first contribution.  So that's a bit of a challenge.

**Comment by exarkun** [comment]
> To that end, I was originally imagining just adding a collections.deque(maxlen=10000) (or whatever limit we choose) somewhere in Gridsync that WebSocketEliotLogReader could append() lines/messages to (and from which the log exporter UI would read later if/when the user needs to export).

This is probably what I'll go with.  I may hide the deque behind a different interface, though.  I think that compressing the logs in memory may actually make sense at some point, to allow for a greater volume to be retained (and the logs compress really well).  So an interface that allows for storage as compressed strings would be nice.  But to reiterate my comment in the description, I'm not planning to actually implement any such compression right now.

**Comment by crwood** [comment]
Ah, so you _are_ intending on submitting a PR for this? I actually started work on this last night (in the `173.consume-tahoe-logs` branch -- which works but is still a WIP) and was planning on finishing it through today so if you have other stuff to do, don't feel obligated to work on this (unless you really want to, of course). :)

**Comment by exarkun** [comment]
Guess I should have made it clear I planned to work on it (issue ownership might be one way to indicate but github won't let me assign gridsync issues).  But I haven't gotten very far so I'll let you finish up your work.  I have one small cleanup that I might push separately.

**Comment by exarkun** [comment]
Or we could pair on finishing what you started, if you want
