### ISSUE TITLE
rephrase "share this computer's free space"

### ISSUE THREAD

**Issue by leif** [gridsync/gridsync#24]
I'm not sure what this should say precisely but it should make it clear somehow that this option should only be enabled on computers that are expected to stay online most of the time.

**Comment by crwood** [comment]
Hi leif! Thanks for bringing this to light!

I'm most likely going to be moving the initial activation of this option to the new "grid setup" wizard in which we could convey this information to the user much earlier on (perhaps via a prompt/radial option that reads something along the lines of "This computer is expected to be connected to the Internet most of the time; share its free space with other users in the grid.").

Alternatively, with the new ``peers.preferred`` setting (and thanks for that, by the way!), we might be able to just adjust storage node selection on the client's side dynamically (e.g., by parsing the WUI welcome page and reconfiguring accordingly) preferring nodes with higher proven uptimes. This would at least help to minimize the odds of placing shares on a node that is frequently offline.

In any case, I'll be consulting with the UX pros about this soon-ish and will see if they have any suggestions for how to best present this option (and, especially, its consequences) to the end user.

**Comment by crwood** [comment]
Closing this, as the user-facing option to provide storage service back to the grid was removed some time ago (on the grounds that keeping it around would be more likely to degrade other users' experience due to placing shares on laptops that would go offline, etc.).
