### ISSUE TITLE
AppImages contain numerous duplicate libraries

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#251]
After unpacking the Gridsync AppImage with the `--appimage-extract` flag, I noticed that the resultant `squashfs-root` directory contains multiple copies of some libraries -- probably as a result of PyInstaller's "onedir" mode copying them in the root directory while `linuxdeploy` insists that they be placed in `AppDir/usr/lib`. Because the duplicate libraries increase the size of the AppImage file significantly, they should be removed if possible (and the deduplicated/smaller AppImage should be tested for any regressions resulting from this).

**Comment by probonopd** [comment]
Replacing copies with symlinks might be easiest.

**Comment by crwood** [comment]
Hi @probonopd! Thanks for popping in -- and thanks for all of your work on AppImage! :)

I've replaced the superfluous library copies with symlinks (in #253) as you suggest, which reduced the resultant filesize significantly. Cheers!
