### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [gridsync/gridsync#252]
Please provide an AppImage file (and ideally also the corresponding zsync file) for download on https://github.com/gridsync/gridsync/releases.

> Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

Source: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by crwood** [comment]
An AppImage is now available for [the latest v0.4.3 release](https://github.com/gridsync/gridsync/releases/tag/v0.4.3).

**Comment by probonopd** [comment]
Thank you very much.
