### ISSUE TITLE
NixOS packaging needs to supply Twisted 21.7.0 or newer

### ISSUE THREAD

**Issue by exarkun** [gridsync/gridsync#378]
0a77277e849657ae45ca468bbb91fca830bfe4e1 bumped the required version of Twisted up to 21.7.0 which nixpkgs does not yet provide.  The newer version of nixpkgs which could supply Twisted has some incompatible Qt changes that also need to be addressed in order for pyqtchart to continue to work.

**Comment by crwood** [comment]
I see that you were able [get Twisted 21.7.0 merged into nixpkgs](https://github.com/NixOS/nixpkgs/pull/132900) -- that's great!

What are the "incompatible Qt changes" you've referenced? Is there any further work that needs to be done here? (I've merged https://github.com/gridsync/gridsync/pull/379 but am unsure whether that's sufficient to address the Qt issues you allude to.)

**Comment by exarkun** [comment]
These were changes in nixpkgs where the Qt packages have been upgraded and shuffled around a little bit.  However, I think it is probably safe to say that https://github.com/NixOS/nixpkgs/pull/132900 resolves *this* issue.
