### ISSUE TITLE
Magic-Folder and ZKAPAuthorizer are migrating to Python 3

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#432]
Two of the applications that Gridsync currently depends on and bundles -- namely Tahoe-LAFS-with-ZKAPAuthorizer and Magic-Folder -- are in the process of being [ported](https://github.com/PrivateStorageio/ZKAPAuthorizer/pull/278) to [Python 3](https://github.com/LeastAuthority/magic-folder/pull/603). Because Gridsync is already python3-only -- and because building and shipping two separate python2-only binary packages alongside Gridsync has been and continues to be an enormous burden -- Gridsync should switch to building and shipping python3-based Tahoe-LAFS and Magic-Folder binaries as soon as it it feasible to do so.

As an added bonus, once this process has been completed, it should be possible to build PyInstaller ["multipackage bundles"](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#multipackage-bundles), significantly reducing the overall size of the Gridsync application bundle.

**Comment by exarkun** [comment]
Tahoe-LAFS on Python 3 suffers from https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3854 which will prevent GridSync from making some requests (at least requests to the `calculate-price` endpoint).

**Comment by crwood** [comment]
PR to fix the above Tahoe-LAFS bug: https://github.com/tahoe-lafs/tahoe-lafs/pull/1168 (copied here to make it slightly easier to follow)
