### ISSUE TITLE
Drive mounting on Windows

### ISSUE THREAD

**Issue by tylernguyen** [gridsync/gridsync#44]
An option to mount the directory as a drive within Windows would be very useful.

**Comment by crwood** [comment]
Hi there! Thanks for the feature-request!

Although I there are no immediate plans to implement drive-mounting directly in Gridsync (as it is not well supported by Tahoe-LAFS upstream) it is nevertheless something I would like to see at _some_ point in the future -- ideally before the price of storage diminishes to zero. :)

In the meantime, it may be worth mentioning that Tahoe-LAFS nominally supports an [SFTP frontend](https://github.com/tahoe-lafs/tahoe-lafs/blob/master/docs/frontends/FTP-and-SFTP.rst) (which _could_ provide an avenue for mounting a Tahoe-LAFS directory locally via [libfuse/sshfs](https://github.com/libfuse/sshfs)). Last time I tried it, however, the performance was especially poor (as expected) and I'm not sure how or whether this would work in Windows specifically.. Maybe [Dokan SSHFS](https://github.com/dokan-dev/dokan-sshfs) would be useful here?

Also worth mentioning is the [PyFilesystem](https://github.com/PyFilesystem) project. While I'm not sure what the state of the project is currently (and have never used it with Windows), I do recall an older version of it [allegedly working with Tahoe-LAFS](https://tahoe-lafs.org/trac/tahoe-lafs/wiki/pyFilesystem).
