### ISSUE TITLE
Magic-Folder is now on PyPI

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#443]
Thanks to @meejah, releases for [the Magic-Folder project](https://github.com/LeastAuthority/magic-folder/) are now [published on PyPI](https://github.com/LeastAuthority/magic-folder/). Gridsync should switch to shipping/depending on these more "official" versioned releases -- rather than the GitHub-hosted-tarballs-corresponding-to-an-arbitrary-commit that Gridsync is currently pinning).

**Comment by exarkun** [comment]
Let's be clear about the downside of this.  By depending on releases on PyPI, we increase the turn-around time to ship any fixes and we add an obstacle to integration testing changes as they are developed.

**Comment by crwood** [comment]
Yes, I should have been more clear: there's no need for Gridsync to _only_ or _exclusively_ depend on PyPI releases of Magic-Folder; the tooling/option to ship (or test against) non-release/non-tagged revisions will always/still remain available. In either case, [the same line in the same file must be updated](https://github.com/gridsync/gridsync/commit/e226c9bc1d06d9c882c064443bfaf4d127946ac3) to set/update the dependency before generating the pins/hashes -- and that line should generally point to "whichever version of Magic-Folder we currently want to test or ship". Put differently: it doesn't really matter whether that version is a tagged release published to PyPI or some GitHub-hosted tarball corresponding to some arbitrary/untagged revision (but, _in this moment_, the version of Magic-Folder we want to test/ship just so happens to be the one that was just released on PyPI).
