### ISSUE TITLE
Change magic-wormhole appid

### ISSUE THREAD

**Issue by meejah** [gridsync/gridsync#49]
Since `tahoe` uses the appid `tahoe-lafs.org/invite` for the `tahoe invite` command, we should switch gridsync (in concert with S4) to use that same appid by default. See https://github.com/LeastAuthority/leastauthority.com/issues/705

**Comment by crwood** [comment]
Fixed by [dd0aa47](https://github.com/gridsync/gridsync/commit/dd0aa472e5b879e16cf8808db088358fa73bda64)
