### ISSUE TITLE
`python-challenge-bypass-ristretto` has dropped support for macOS 10.14

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#505]
The [latest PyPI release](https://pypi.org/project/python-challenge-bypass-ristretto/2022.6.30/#files) of the `python-challenge-bypass-ristretto` library has [dropped support](https://github.com/LeastAuthority/python-challenge-bypass-ristretto/commit/c11d4a7bd424f8279970af9e34bb4d561b0d6162) for macOS 10.14. The Gridsync project, however, currently maintains and depends on a macOS 10.14 buildbot-worker in order to [maintain forward-compatibility for PyInstaller builds](https://pyinstaller.org/en/stable/usage.html#making-macos-apps-forward-compatible).

Accordingly, the Gridsync project should either update the macOS 10.14 buildbot-worker/CI configuration to (reproducibly) build the rust-based `python-challenge-bypass-ristretto` library _or_ explicitly drop support for macOS 10.14 (i.e., update builders to target macOS 10.15 and higher) -- preferably the latter...

**Comment by exarkun** [comment]
There are only trivial changes in the latest release of `python-challenge-bypass-ristretto` (basically only packaging and one new API alias) so GridSync could also use the previous release.  Perhaps for long enough that macOS 10.14 really becomes irrelevant?

**Comment by exarkun** [comment]
(Oh, I didn't read carefully enough - I see that you would like to drop macOS 10.14 support now if you can .. good luck!)

**Comment by crwood** [comment]
Yes, 10.14 has been EOL for 9 months now and should probably be dropped soon anyway. Unfortunately, macOS versions after 10.14 are considerably more cumbersome to virtualize -- at least with VirtualBox (which seems to have all sorts of issues with APFS volumes) but maybe this state-of-affairs improved recently...

In the interim, I will [pin](https://github.com/gridsync/gridsync/pull/506) to 2021.7.12 (since, as you point out, the changes between that and the latest release are rather trivial).
