### ISSUE TITLE
The magic-wormhole-based invite documentation suggests unworkable use of `wormhole` cli

### ISSUE THREAD

**Issue by exarkun** [gridsync/gridsync#51]
`docs/invite.rst` gives an example of using `wormhole` on the command line for sending an invite to a GridSync user.  However, the new invite protocol involves two rounds of messages and the `wormhole` command won't (and can't) send both of these.

**Comment by crwood** [comment]
Gridsync actually still supports receiving (but not sending) invites using the [old, xfer_util-based "protocol"](https://github.com/gridsync/gridsync/blob/fb229554fc461eae138b26eb8448bf5e94c6fda2/gridsync/invite.py#L184) and so the example given in `doc/invite.rst` will still work as described. However this doc should be re-written anyway -- both to point out that the old way is deprecated and to encourage users to use `tahoe invite` in place of rolling their own solution.

I'll update this soon -- probably within the next few days. Thanks!
