### ISSUE TITLE
Report: "Crash when disabling `Start automatically on login`"

### ISSUE THREAD

**Issue by crwood** [gridsync/gridsync#512]
An unnamed-unless-they-wish-to-be-named user reports:

>disabling Start automatically on login lead to a crash on Windows 10 on my personal laptop a couple of times.
>
>To me it looks like there is some sort of error or exception happening that is not handled.
Looking at the code, maybe it might be something like [this os.remove()](https://github.com/gridsync/gridsync/blob/0b890e039275f261b868511decdeaa776733e924/gridsync/desktop.py#L213).

**Comment by hacklschorsch** [comment]
Give me names all you like! Thanks for your great work.
