### ISSUE TITLE
Can't exit app without entering invite code

### ISSUE THREAD

**Issue by hacklschorsch** [gridsync/gridsync#651]
Installed GridSync to test the installer, started the app after installation (out of the installer) and then tried to quit.

GridSync shows below dialogue.

<img width="305" alt="image" src="https://github.com/gridsync/gridsync/assets/454605/73863824-7c0b-4056-aabe-e38faeee1aa2">

Expected behavior: When I click *Yes* GridSync should exit.
Actual behavior: The modal dialog disappears just as if I had clicked *No*. GridSync keeps running.

Proposed fix: Remove the modal dialogue.

**Comment by crwood** [comment]
Thanks for filing this.

I can confirm/reproduce the same behavior with Qt6-based builds (but not Qt5-based ones). I wonder if this is related to https://github.com/gridsync/gridsync/issues/609?

In any case, maybe it's time to prioritize fixing this... I'll try debugging further.

**Comment by hacklschorsch** [comment]
Thanks @crwood !
