### ISSUE TITLE
Recovery shows empty button while loading

### ISSUE THREAD

**Issue by hacklschorsch** [gridsync/gridsync#676]
(Translation of DE conversation follows)

> Hi, I'm trying out a few things at the moment and when restoring with the recovery key, it just displayed a button with no content during the loading process. Unfortunately I can't provide a screenshot right now, but the system info

Original:
```
Hallo, ich probiere gerade bisschen rum und bei mir hat es
gerade bei der Wiederherstellung mit dem recovery key
einen Button ohne Inhalt während des Ladeprozess
angezeigt. Ich kann dazu leider gerade keinen Screenshot
liefern, aber die Systeminfo:

       _,met$$$$$gg.          user@onemoretest 
    ,g$$$$$$$$$$$$$$$P.       ---------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64 
 ,$$P'              `$$$.     Kernel: 6.1.75-1.qubes.fc32.x86_64 
',$$P       ,ggs.     `$$b:   Uptime: 11 mins 
`d$$'     ,$P"'   .    $$$    Packages: 1590 (dpkg) 
 $$P      d$'     ,    $$P    Shell: bash 5.1.4 
 $$:      $$.   -    ,d$$'    Resolution: 1368x768 
 $$;      Y$b._   _,d$P'      DE: GNOME 
 Y$$.    `.`"Y$$$$P"'         WM: Qubes 
 `$$b      "-.__              Theme: Adwaita [GTK2/3] 
  `Y$$                        Icons: Adwaita [GTK2/3] 
   `Y$$.                      Terminal: gnome-terminal 
     `$$b.                    CPU: Intel i5-3320M (2) @ 2.594GHz 
       `Y$$b.                 Memory: 242MiB / 783MiB 
          `"Y$b._
              `"""
```

**Comment by crwood** [comment]
Without any further details, it is difficult to provide further assistance to this person. Can they provide a debug log and/or the steps they took to reproduce the issue?

**Comment by hacklschorsch** [comment]
Probably not anymore - also please note that the process did work.
This seems to be more of a cosmetic / confidence decreasing issue than a bug causing a fatal error.  If you just hold still long enough, recovery seems to complete

**Comment by crwood** [comment]
That is good to know -- thanks!

Do you happen to know which "button with no content" they might be referring to here?

**Comment by hacklschorsch** [comment]
My contact has sent a screenshot:

![signal-2024-02-22-150627_003](https://github.com/gridsync/gridsync/assets/454605/d3f3244e-d4b5-4e9b-9c46-d6c980a7520f)

**Comment by crwood** [comment]
Thanks for the screenshot. I know which button you/they are referring to now.

Fixed by https://github.com/gridsync/gridsync/pull/680

**Comment by hacklschorsch** [comment]
Thanks!
